general {
    disable_loading_bar = true
    hide_cursor = true
}

background {
    monitor =
    color = rgba(0, 0, 0, 0.8)
    blur_passes = 2
    blur_size = 4
}

input-field {
    monitor =
    size = 300, 50
    outline_thickness = 2
    inner_color = rgba(0, 0, 0, 0.8)
    outer_color = rgba(33, 204, 255, 0.8)
    font_color = rgb(255, 255, 255)
    placeholder_text = <i>Password</i>
    position = 0, -80
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%H:%M")"
    font_size = 72
    font_family = Sans
    color = rgba(255, 255, 255, 0.9)
    position = 0, 80
    halign = center
    valign = center
}
